/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VacacionesRouteImport } from './routes/vacaciones'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as JornadasRouteImport } from './routes/jornadas'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AusenciasRouteImport } from './routes/ausencias'
import { Route as IndexRouteImport } from './routes/index'

const VacacionesRoute = VacacionesRouteImport.update({
  id: '/vacaciones',
  path: '/vacaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadasRoute = JornadasRouteImport.update({
  id: '/jornadas',
  path: '/jornadas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AusenciasRoute = AusenciasRouteImport.update({
  id: '/ausencias',
  path: '/ausencias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ausencias': typeof AusenciasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/jornadas': typeof JornadasRoute
  '/usuarios': typeof UsuariosRoute
  '/vacaciones': typeof VacacionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ausencias': typeof AusenciasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/jornadas': typeof JornadasRoute
  '/usuarios': typeof UsuariosRoute
  '/vacaciones': typeof VacacionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ausencias': typeof AusenciasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/jornadas': typeof JornadasRoute
  '/usuarios': typeof UsuariosRoute
  '/vacaciones': typeof VacacionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ausencias'
    | '/configuracion'
    | '/jornadas'
    | '/usuarios'
    | '/vacaciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ausencias'
    | '/configuracion'
    | '/jornadas'
    | '/usuarios'
    | '/vacaciones'
  id:
    | '__root__'
    | '/'
    | '/ausencias'
    | '/configuracion'
    | '/jornadas'
    | '/usuarios'
    | '/vacaciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AusenciasRoute: typeof AusenciasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  JornadasRoute: typeof JornadasRoute
  UsuariosRoute: typeof UsuariosRoute
  VacacionesRoute: typeof VacacionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vacaciones': {
      id: '/vacaciones'
      path: '/vacaciones'
      fullPath: '/vacaciones'
      preLoaderRoute: typeof VacacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornadas': {
      id: '/jornadas'
      path: '/jornadas'
      fullPath: '/jornadas'
      preLoaderRoute: typeof JornadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ausencias': {
      id: '/ausencias'
      path: '/ausencias'
      fullPath: '/ausencias'
      preLoaderRoute: typeof AusenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AusenciasRoute: AusenciasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  JornadasRoute: JornadasRoute,
  UsuariosRoute: UsuariosRoute,
  VacacionesRoute: VacacionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
